# Step 1: Build the React app
FROM node:22 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Step 2: Serve the built app using nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# Start nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
